### PR TITLE
Add auth in skywalking plugin

### PR DESCRIPTION
**Pull request by xonze**

### CODE REVIEW

**Review by xonze — COMMENTED** [review]
review ok

**Comment by benjaminhuo** [comment]
@tpiperatgod Do we need to add `Auth` to `provider` ?https://github.com/OpenFunction/OpenFunction/blob/main/config/configmap/openfunction-config.yaml#L20

**Comment by tpiperatgod** [comment]
> @tpiperatgod Do we need to add `Auth` to `provider` ?https://github.com/OpenFunction/OpenFunction/blob/main/config/configmap/openfunction-config.yaml#L20

If this PR is merged, we have to add `provider.Auth` to `openfunction-config`. But I think we can do this after v0.6.0 @xonze Please let us know if this parameter will affect the functionality of the current `skywalking` plugin? Thx.

**Comment by benjaminhuo** [comment]
What other changes should be made except the configmap?
The `Auth` param could be commented out by default in the configmap.
Do we need to change the go code in OpenFunction?

@tpiperatgod

**Comment by tpiperatgod** [comment]
> What other changes should be made except the configmap? The `Auth` param could be commented out by default in the configmap. Do we need to change the go code in OpenFunction?
> 
> @tpiperatgod

Yes, we need to change the structure of the `tracingProvider`.
https://github.com/OpenFunction/OpenFunction/blob/main/pkg/core/serving/common/functioncontext.go#L60-L63

**Comment by benjaminhuo** [comment]
Looks like `Auth` is optional for Skywalking. @arugal @xonze , right?
@tpiperatgod OpenFunction is still in v0.6.0-rc.0, we still have time to add this to the final v0.6.0

**Review by arugal — CHANGES_REQUESTED** [review]
Now that go2sky already support [SW_AGENT_AUTHENTICATION](https://github.com/SkyAPM/go2sky#supported-environment-variables), I think `auth` should be set via an environment variable

**Comment by benjaminhuo** [comment]
Environment variable could be set by the `params` under function serving:
https://github.com/OpenFunction/OpenFunction/blob/main/apis/core/v1beta1/function_types.go#L152

**Comment by xonze** [comment]
@arugal @benjaminhuo ok,this pr close

**Pull request closed without merging**
